### ISSUE TITLE
no login due censorship?

### ISSUE THREAD

**Issue by farbodrashidi** [fandoghpaas/fandogh-cli#100]
Hey there,

Just successfully installed your CLI tool on Archlinux, after installing I tried to log in but I get this error:

-------------------------

farbod@universe ~> fandogh login
                   
username: pharbod
password: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 357, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 387, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 383, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 266, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/fandogh", line 11, in <module>
    sys.exit(base())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/fandogh_cli/base_commands.py", line 36, in invoke
    raise exp
  File "/usr/lib/python3.6/site-packages/fandogh_cli/base_commands.py", line 23, in invoke
    return super(FandoghCommand, self).invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/fandogh_cli/fandogh.py", line 31, in login
    message = present(lambda: handle_token(), post='Logged in successfully')
  File "/usr/lib/python3.6/site-packages/fandogh_cli/presenter.py", line 47, in present
    data = data_provider()
  File "/usr/lib/python3.6/site-packages/fandogh_cli/fandogh.py", line 31, in <lambda>
    message = present(lambda: handle_token(), post='Logged in successfully')
  File "/usr/lib/python3.6/site-packages/fandogh_cli/fandogh.py", line 28, in handle_token
    token_obj = get_token(username, password)
  File "/usr/lib/python3.6/site-packages/fandogh_cli/fandogh_client/__init__.py", line 181, in get_token
    response = requests.post(base_url + 'tokens', json={'username': username, 'password': password})
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))

--------------------

and after this I tried to run it under tor (torify), its Iran after all you know!

farbod@universe ~> systemctl start tor 

farbod@universe ~> torify fandogh login
username: pharbod
password: 
Logged in successfully

then I can only run commands via torify.
thanks.

**Comment by s-soroosh** [comment]
Hi pharbod,

Could you please send me the response of the following curl command

‘’’
curl http://fandogh.cloud:8080
‘’’

**Comment by farbodrashidi** [comment]
sure thing, there you go:

[farbod@universe ~]$ curl http://fandogh.cloud:8080
curl: (56) Recv failure: Connection reset by peer

but of course:
[farbod@universe ~]$ curl https://fandogh.cloud/
[farbod@universe ~]$ curl https://fandogh.cloud:443

returns the full page (source) result in terminal.

**Comment by s-soroosh** [comment]
@pharbod interesting, I guess there is either a firewall running in your network or a http proxy is enabled. 

However we will enabled the https in the next version of the CLI (probably tomorrow). that must resolve the problem you are facing. 

Thank you so much for reporting this issue Farbod jan :)

**Comment by s-soroosh** [comment]
Hi @pharbod,

We just published the new cli version `0.4.9` that should not have the problem you issued anymore.
May I kindly ask you to test the new version whenever you could and confirm it?

Thanks

**Comment by s-soroosh** [comment]
Hi @pharbod, 
I'm going to close this issue. 
Feel free to reissue it if you still have this problem.

Thanks

**Comment by farbodrashidi** [comment]
I confirm that the issue is now fixed up to version 0.4.10:

farbod@universe ~> fandogh login
username: pharbod
password: 
Logged in successfully

thanks for the awesome service ;)

**Comment by s-soroosh** [comment]
Great @pharbod, 
Looking forward to see you  are actively using the fandogh and let us improve it with your valuable feedbacks.
