### ISSUE TITLE
[Solved] Cannot connect to mongoDB

### ISSUE THREAD

**Issue by sadra** [fandoghpaas/fandogh-cli#171]
I've deployed a mongo service with the following command:

```bash
fandogh service deploy \
 --image library/mongo \
 --version latest \
 --port 27017 \
 --name mongo-service-name
```
But I can't connect to database!

- with `mongodb+srv://mongo-service-name-account.fandogh.cloud/`
I get:
```bash
connection error: { Error: querySrv ENODATA _mongodb._tcp.mongo-service-name-account.fandogh.cloud
    at errnoException (dns.js:28:10)
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:216:19)
  code: 'ENODATA',
  errno: 'ENODATA',
  syscall: 'querySrv',
  hostname: '_mongodb._tcp.mongo-service-name-account.fandogh.cloud' }
```

- and with `mongodb://public-mongo-sadra.fandogh.cloud/`
I get:
```bash
connection error: { Error: failed to connect to server [mongo-service-name-account.fandogh.cloud:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 165.227.244.57:27017]
    at Pool.<anonymous> (/MY_DIR/node_modules/mongodb-core/lib/topologies/server.js:564:11)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:191:7)
    at Connection.<anonymous> (/MY_DIR/node_modules/mongodb-core/lib/connection/pool.js:317:12)
    at Object.onceWrapper (events.js:293:19)
    at emitTwo (events.js:106:13)
    at Connection.emit (events.js:194:7)
    at Socket.<anonymous> (/MY_DIR/node_modules/mongodb-core/lib/connection/connection.js:246:50)
    at Object.onceWrapper (events.js:293:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at emitErrorNT (net.js:1289:8)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ] }
```

So what's the solution?

**Comment by MahdiZareie** [comment]
Dear Sadra,
Unfortunately it's not possible to use a non-HTTP connection to connect to your MongoDB from outside of your fandogh namespace internal network at the moment.
any service which needs to query MongoDB needs to be inside your namespace private network, so you should consider running your service on Fandogh too.

**Comment by sadra** [comment]
So, I how can I access throw internal service?
What should I user here:
`mongodb://WHAT_SHOULD_I_PUT_HERE/DB_NAME`

**Comment by s-soroosh** [comment]
@sadra , your services inside your namespace are accessible through their names.

So if you mongo service name is `mongo1`, then your connection string will be sth like:
`mongodb://mongo1/DB_NAME`

**Comment by sadra** [comment]
## Solution

So if you have a `database` or `internal` service, just use the `service name` into another service that you want.
Like here, I want to use `MongoDB` in my `NodeJs` service; my mongo service name is `MY-MONGO-SERVICE`, so I connect with:
`mongoose.connect('mongodb://MY-MONGO-SERVICE/DB_NAME')`

**Comment by s-soroosh** [comment]
Wdym with service name in your image?
Service name is defined in deployment time either in manifest or via —name option to deploy command.

**Comment by dannyrajakarunanayake** [comment]
i got this error

(node:1168) UnhandledPromiseRejectionWarning: Error: queryTxt EBADNAME emaily-uwsj6.mongodb.net
    at QueryReqWrap.onresolve [as oncomplete] (dns.js:206:19)
