### ISSUE TITLE
ValueError: Timezone offset does not match system offset

### ISSUE THREAD

**Issue by almohress** [fandoghpaas/fandogh-cli#289]
I've installed fandogh-cli via `pip install fandogh-cli --upgrade` on python virtual environment, but `fandogh --help` returns:
```python
Traceback (most recent call last):
  File "/home/almohress/.virtualenvs/fandogh/bin/fandogh", line 5, in <module>
    from fandogh_cli.fandogh import base
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/fandogh_cli/fandogh.py", line 3, in <module>
    from fandogh_cli.namespace_commands import namespace
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/fandogh_cli/namespace_commands.py", line 2, in <module>
    from fandogh_cli.config import get_user_config, set_cluster_namespace, get_cluster_namespace
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/fandogh_cli/config.py", line 3, in <module>
    from fandogh_cli.utils import makedirs
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/fandogh_cli/utils.py", line 10, in <module>
    USER_TIMEZONE = pytz.timezone(tzlocal.get_localzone().zone)
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/tzlocal/unix.py", line 165, in get_localzone
    _cache_tz = _get_localzone()
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/tzlocal/unix.py", line 90, in _get_localzone
    utils.assert_tz_offset(tz)
  File "/home/almohress/.virtualenvs/fandogh/lib/python3.9/site-packages/tzlocal/utils.py", line 46, in assert_tz_offset
    raise ValueError(msg)
ValueError: Timezone offset does not match system offset: -14400 != 16200. Please, check your config files.
```

**Comment by almohress** [comment]
there was a timezone conflict on my OS and I fixed that
