### ISSUE TITLE
Make Directory Traceback on login

### ISSUE THREAD

**Issue by enayatinfo** [fandoghpaas/fandogh-cli#3]
Traceback (most recent call last):
  File "/usr/local/bin/fandogh", line 11, in <module>
    sys.exit(base())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/fandogh_cli/fandogh.py", line 156, in login
    persist_token(token_obj)
  File "/Library/Python/2.7/site-packages/fandogh_cli/config.py", line 32, in persist_token
    os.makedirs(os.path.dirname(credentials_path), exist_ok=True)
TypeError: makedirs() got an unexpected keyword argument 'exist_ok'

Os: Mac Os
Python V: 2.7

**Comment by s-soroosh** [comment]
Thanks for reporting the issue. 
As mentioned in the readme, at the moment fandogh cli only support python 3.5+.

Can you upgrade your python and test it again?

**Comment by enayatinfo** [comment]
its ok on python 3.5+
