### ISSUE TITLE
Cannot destroy service

### ISSUE THREAD

**Issue by mrkhatami95** [fandoghpaas/fandogh-cli#4]
```
> D:\docker>fandogh service destroy  --name hello-world
> Traceback (most recent call last):
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\MR\AppData\Local\Programs\Python\Python36\Scripts\fandogh.exe\__main__.py", line 9, in <module>
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
>     return self.main(*args, **kwargs)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
>     rv = self.invoke(ctx)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
>     return callback(*args, **kwargs)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\fandogh_cli\fandogh.py", line 147, in service_destroy
>     response = destroy_service(service_name, token)
>   File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\fandogh_cli\fandogh_client\__init__.py", line 81, in destroy_service
>     raise Exception(response.text)
> Exception: <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
> <html><head>
> <title>403 Forbidden</title>
> </head><body>
> <h1>Forbidden</h1>
> <p>You don't have permission to access http://fandogh.cloud:8080/api/webapp/services/hello-world
> on this server.</p>
> </body></html>
```

**Comment by mrkhatami95** [comment]
Trying to destroy published app showing success message but not working.


```
D:\docker\test>fandogh service destroy --name hello-world
Service destroyed successfully.

D:\docker\test>fandogh service deploy --app test --name test --version 1
Traceback (most recent call last):
  File "c:\users\mr\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\MR\AppData\Local\Programs\Python\Python36\Scripts\fandogh.exe\__main__.py", line 9, in <module>
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\fandogh_cli\fandogh.py", line 121, in deploy
    response = deploy_service(app, version, name, token)
  File "c:\users\mr\appdata\local\programs\python\python36\lib\site-packages\fandogh_cli\fandogh_client\__init__.py", line 63, in deploy_service
    raise Exception(response.text)
Exception: "You already have one running service. Please destroy if you want to deploy a new one."
```

**Comment by mrkhatami95** [comment]
```
D:\docker\test>fandogh service list
+-------------+-----------------------------------------------------+----------+
|    name     |                     start date                      |  state   |
+-------------+-----------------------------------------------------+----------+
| hello-world |             2018-05-08T08:31:13.909070Z             | SHUTDOWN |
| hello-world |             2018-05-08T08:46:02.705621Z             | SHUTDOWN |
|   mr-test   |             2018-05-08T08:52:50.676924Z             | RUNNING  |
+-------------+-----------------------------------------------------+----------+
```

**Comment by s-soroosh** [comment]
Hi @mrkhatami95,
it seems you had a running service with name `mr-test` that prevented you from having another service running with a different name.  right?

**Comment by mrkhatami95** [comment]
Hi Soroosh,
Yes, It solved by shutting down that :+1:
