### ISSUE TITLE
"OSError: [Errno 17] File exists" thrown upon first execution

### ISSUE THREAD

**Issue by ashkantaravati** [fandoghpaas/fandogh-cli#60]
### **Situation:**
Created empty config.yml file in designated path "~/.fandogh" then exception was thrown

### **Solution:**
Manual Creation of "~/.fandogh/credentials.yml" solved the problem

### **Machine Info:**
Python 2.7.14
Ubuntu MATE 17.10 64-bit

### **StackTrace:**
```
ashkan@ShepherdDog:~/.fandogh$ fandogh login
Traceback (most recent call last):
  File "/usr/local/bin/fandogh", line 11, in <module>
    load_entry_point('fandogh-cli==0.3.6', 'console_scripts', 'fandogh')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 564, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2662, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2316, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2322, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/fandogh.py", line 5, in <module>
    from .image_commands import image
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/image_commands.py", line 4, in <module>
    from .base_commands import FandoghCommand
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/base_commands.py", line 9, in <module>
    from fandogh_cli.config import get_user_config
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/config.py", line 53, in <module>
    _config_repository = _initialize_configuration()
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/config.py", line 49, in _initialize_configuration
    'user': ConfigRepository(os.path.join(os.path.expanduser('~'), '.fandogh', 'credentials.yml'))
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/config.py", line 15, in __init__
    configurations = self._load_from_file(configuration_file)
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/config.py", line 24, in _load_from_file
    makedirs(os.path.dirname(configuration_file))
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/utils.py", line 48, in makedirs
    _makedirs(name, mode)
  File "/usr/local/lib/python2.7/dist-packages/fandogh_cli/utils.py", line 46, in _makedirs
    os.mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/ashkan/.fandogh'

```

**Comment by s-soroosh** [comment]
Thanks @ashkantaravati for reporting the issue. 

We will fix this issue in the next release of the CLI.

**Comment by s-soroosh** [comment]
This bug is version `0.3.7` has been fixed.
